title: Automated Scientific Discovery of Mind and Brain (ASDMB)
author: Sebastian Musslick, Jonathan Cohen, Younes Strittmatter
logo: _static/logo.svg
favicon: _static/logo.svg
copyright: "© 2025"

execute:
  execute_notebooks: "off"     # keep CI fast & predictable


repository:
  url: https://github.com/AutoResearch/ASDMB-Workshop/
  path_to_book: ASDMB-book
  branch: main

html:
  theme: pydata_sphinx_theme    # important: works fine set here for Jupyter Book
  use_repository_button: true

launch_buttons:
  colab_url: "https://colab.research.google.com"
  notebook_interface: "classic"

sphinx:
  extra_css:
    - custom.css
    - css/schedule.css
  config:
    html_extra_path:
      - content/external
    html_theme: pydata_sphinx_theme
    # theme options
    html_theme_options:

      logo:
        text: "ASDMB"
      show_nav_level: 2            # show chapters + sections in sidebar
      navigation_depth: 4
      header_links_before_dropdown: 6
      navbar_start: ["navbar-logo"]
      navbar_center: ["navbar-nav"]
      navbar_end:
        - icon-links
      icon_links:
        - name: GitHub
          url: https://github.com/younesStrittmatter/princeton-ASDMB
          icon: fa-brands fa-github
      secondary_sidebar_items: []  # cleaner right side
      show_prev_next: false
    # citations (optional)



